### ISSUE TITLE
403 link on the installation page

### ISSUE THREAD

**Issue by hhhorb** [BunsenLabs/website#11]
https://www.bunsenlabs.org/installation.html#package-based-install

>You may also choose to follow our repository set-up instructions and include our package repository into your existing Debian system. 

But the 'instructions' link to http://eu.pkg.bunsenlabs.org/ gives a 403 "Access denied" warning page. Or is this caused by IP being on a blocklist?

**Comment by 2ion** [comment]
Ah, the linked page was dropped a long time ago. Fixed.
