### ISSUE TITLE
Website/repo outage

### ISSUE THREAD

**Issue by hhhorb** [BunsenLabs/website#21]
The BL forums and homepage fail to load in a browser, and apt update fails due to the BunsenLabs repo(s).

>Err:6 https://pkg.bunsenlabs.org/debian lithium InRelease  
  Could not connect to pkg.bunsenlabs.org:443 (2a01:4f8:c17:2c09::2)

**Comment by 2ion** [comment]
Does the problem still persist? No problems here (and there weren't any judging from the Germany-local monitoring) . Hetzner had an outage in their cloud network today in the location our kelaino.bunsenlabs.org server is in, so traffic might still be affected, coming from the US. See https://www.hetzner-status.de/en.html.

You could try to force ipv6 to off and try connecting using ipv4.

If it still doesn't work, you could check the output of mtr -4 or mtr -6 pkg.bunsenlabs.org and check where the network fails.

**Comment by hhhorb** [comment]
All good when checking now. Probably just a temporary server issue.
